# 服务端口
server:
  port: 8099
# 日子配置文件位置
logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: 123
    executor:
      appname: own-job-executor
      address:
      ip:
      port: 6666
      logpath: /Users/sunxiaojian/JavaWorkSpace/xxl-job-2.4.0
      logretentiondays: 30

